### ISSUE TITLE
Chat DB Can't open

### ISSUE THREAD

**Issue by Ocean-Moist** [golift/imessage#3]
Hi,

I am fairly new to go and thought this would be a fun side project. 

I built it and am trying to run your example. When ever I run my build I get this:
`[DEBUG] 2020/04/23 10:55:30 opening database: /Users/rohan2020/Library/Messages/chat.db
[DEBUG] 2020/04/23 10:55:30 closing database: /Users/rohan2020/Library/Messages/chat.db
2020/04/23 10:55:30 sqlite.Conn.Prepare: SQLITE_CANTOPEN: unable to open database file (SELECT MAX(rowid) AS id FROM message)`
`
[Process completed]`

SQLITE can not open the chat.db file. Using the sqlite3 command in terminal I can easily open chat.db. 

I am running macOS Catalina Version 10.15 beta.

Thanks!

**Comment by davidnewhall** [comment]
Catalina brought with it some new security measures. Your chat database comes "locked" and nothing but Chat can access it. You have to go into System Preferences -> Security and allow your application "Full Disk Access." 

Thanks Apple.

![Screen Shot 2020-04-23 at 12 16 34 PM](https://user-images.githubusercontent.com/2402929/80140288-94505700-855c-11ea-986a-3e7ce25172c8.png)

**Comment by Ocean-Moist** [comment]
Thank you, 

I had to give terminal access too.
